# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

defaults: &defaults
  docker:
    - image: circleci/android:api-28
  environment:
    JVM_OPTS: -Xmx3200m

default_steps: &default_steps
  steps:
    - checkout:
          path: ~/repo
    - restore_cache:
        key: v1-jars-{{ checksum "build.gradle" }}
    - run:
        name: Download Dependencies
        command: ../gradlew androidDependencies
    - save_cache:
        paths:
          - ~/.gradle
        key: v1-jars-{{ checksum "build.gradle" }}

    #- run: ../gradlew lint test
    - run: ../gradlew clean build bintrayUpload

jobs:
  build_core:
    <<: *defaults
    working_directory: ~/repo/core
    <<: *default_steps

  build_webview:
    <<: *defaults
    working_directory: ~/repo/webview
    <<: *default_steps

  build_google:
    <<: *defaults
    working_directory: ~/repo/google
    <<: *default_steps

  build_facebook:
    <<: *defaults
    working_directory: ~/repo/facebook
    <<: *default_steps

workflows:
  version: 2
  deploy:
    jobs:
      - build_core
      - build_webview:
          requires:
            - build_core
      - build_google:
          requires:
            - build_core
      - build_facebook:
          requires:
            - build_core
          # requires:
          #   - test
          # filters:
          #   tags:
          #     only: /^v.*-alpha\..[0-9]/
          #   branches:
          #     ignore: /.*/
