# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/android:api-28
  environment:
    JVM_OPTS: -Xmx3200m

default_upload_steps: &default_upload_steps
  steps:
    - checkout:
          path: ~/repo
    - restore_cache:
        key: v1-jars-{{ checksum "build.gradle" }}
    - run:
        name: Download Dependencies
        command: ../gradlew androidDependencies
    - save_cache:
        paths:
          - ~/.gradle
        key: v2-jars-{{ checksum "build.gradle" }}
    - run: ../gradlew clean build bintrayUpload

default_build_steps: &default_build_steps
  steps:
    - checkout:
          path: ~/repo
    - restore_cache:
        key: v2-jars-{{ checksum "build.gradle" }}
    - run:
        name: Download Dependencies
        command: ../gradlew androidDependencies
    - save_cache:
        paths:
          - ~/.gradle
        key: v1-jars-{{ checksum "build.gradle" }}
    - run: ../gradlew lint test build

jobs:
  
  build_core:
    <<: *defaults
    working_directory: ~/repo/core
    <<: *default_build_steps

  build_webview:
    <<: *defaults
    working_directory: ~/repo/webview
    <<: *default_build_steps

  build_google:
    <<: *defaults
    working_directory: ~/repo/google
    <<: *default_build_steps

  build_facebook:
    <<: *defaults
    working_directory: ~/repo/facebook
    <<: *default_build_steps

  upload_core:
    <<: *defaults
    working_directory: ~/repo/sdk-core
    <<: *default_upload_steps

  upload_webview:
    <<: *defaults
    working_directory: ~/repo/webview
    <<: *default_upload_steps

  upload_google:
    <<: *defaults
    working_directory: ~/repo/google
    <<: *default_upload_steps

  upload_facebook:
    <<: *defaults
    working_directory: ~/repo/facebook
    <<: *default_upload_steps

default_workflows_filters: &default_workflows_filters
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

default_workflows_tags: &default_workflows_tags
  filters:
    tags:
      only: /.*/

workflows:
  deploy:
    jobs:
      - build_core:
          <<: *default_workflows_tags
      - build_webview:
          <<: *default_workflows_tags
      - build_google:
          <<: *default_workflows_tags
      - build_facebook:
          <<: *default_workflows_tags
      - upload_core:
          requires:
            - build_core
          <<: *default_workflows_filters
      - upload_webview:
          requires:
            - build_webview
          <<: *default_workflows_filters
      - upload_google:
          requires:
            - build_google
          <<: *default_workflows_filters
      - upload_facebook:
          requires:
            - build_facebook
          <<: *default_workflows_filters
