# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/android:api-29
  environment:
    JVM_OPTS: -Xmx3200m

release_upload_steps: &release_upload_steps
  steps:
    - checkout:
        path: ~/repo
    - restore_cache:
        key: v1-jars-{{ checksum "build.gradle" }}
    - run:
        name: Inject Maven signing key
        command: |
          echo $SIGNING_KEY \
            | awk 'NR == 1 { print "signingKey=" } 1' ORS='\\n' \
            >> gradle.properties
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
          - ~/.gradle
        key: v2-jars-{{ checksum "build.gradle" }}
    - run: ./gradlew clean build publishReleasePublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository

snapshot_upload_steps: &snapshot_upload_steps
  steps:
    - checkout:
        path: ~/repo
    - restore_cache:
        key: v1-jars-{{ checksum "build.gradle" }}
    - run:
        name: Inject Maven signing key
        command: |
          echo $SIGNING_KEY \
            | awk 'NR == 1 { print "signingKey=" } 1' ORS='\\n' \
            >> gradle.properties
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
          - ~/.gradle
        key: v2-jars-{{ checksum "build.gradle" }}
    - run: ./gradlew clean build publishSnapshotPublicationToSonatypeRepository

default_build_steps: &default_build_steps
  steps:
    - checkout:
        path: ~/repo
    - restore_cache:
        key: v2-jars-{{ checksum "build.gradle" }}
    - run:
        name: Inject Maven signing key
        command: |
          echo $SIGNING_KEY \
            | awk 'NR == 1 { print "signingKey=" } 1' ORS='\\n' \
            >> gradle.properties
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
          - ~/.gradle
        key: v1-jars-{{ checksum "build.gradle" }}
    - run: ./gradlew lint test build

jobs:

  build_all:
    <<: *defaults
    working_directory: ~/repo
    <<: *default_build_steps

  upload_snapshot:
    <<: *defaults
    working_directory: ~/repo
    <<: *snapshot_upload_steps

  upload_release:
    <<: *defaults
    working_directory: ~/repo
    <<: *release_upload_steps

release_filters: &release_filters
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

snapshot_filters: &snapshot_filters
  filters:
    branches:
      only: master

default_workflows_tags: &default_workflows_tags
  filters:
    tags:
      only: /.*/

workflows:
  circleci:
    jobs:
      - build_all:
          <<: *default_workflows_tags
      - upload_snapshot:
          requires:
            - build_all
          <<: *snapshot_filters
      - upload_release:
          requires:
            - build_all
          <<: *release_filters
