= loginWithPassword


[.signature]
[subs="normal"]
----
client.loginWithPassword(
  <<email>>,
  <<phoneNumber>>,
  <<customIdentifier>>,
  <<password>>,
  <<success>>,
  <<failure>>,
  // Optional arguments
  <<mfaConf>>,
  <<scope>>,
  <<captcha>>
)
----

== About this command

Authenticate the user with the specified identifier (email, phone number, or custom identifier) and password.

A user may identify himself with either his email address or his phone number if the SMS feature is enabled.

When the {cc} protects the login endpoint with a `Captcha`, get a token from Google reCAPTCHA or CaptchaFox in your app, then pass it as <<captcha,`captcha`>>.
The {company} Android SDK does not show the challenge or fetch that token.

.Use a `captcha` token
====
. Enable xref:docs:ROOT:captcha/recaptcha.adoc[reCAPTCHA] or xref:docs:ROOT:captcha/captcha-fox.adoc[CaptchaFox] on the login endpoint in the {cc}.
. In your app, run the Google reCAPTCHA or CaptchaFox challenge and keep the token they return.
. Pass that token as `ReCaptchaToken` or `CaptchaFoxToken` in <<captcha,`captcha`>>.
====

== Examples

[tabs]
====
With an email::
+
--
[source,kotlin]
----
include::example${docname}AndEmail.kt[]
----
--
With a phone number::
+
--
[source,kotlin]
----
include::example${docname}AndPhoneNumber.kt[]
----
--
With a custom identifier::
+
--
[source,kotlin]
----
include::example${docname}AndCustomIdentifier.kt[]
----
--
====

== Parameters

[.options]
[cols="1,3a"]
|===

include::partial$params.adoc[tag="email"]
include::partial$params.adoc[tag="phonenumber"]
include::partial$params.adoc[tag="customIdentifier"]
include::partial$params.adoc[tag="password"]
include::partial$params.adoc[tag="mfaConf"]
include::partial$params.adoc[tag="scope"]
|[[success, success]]success `function` | Callback called once the login has succeeded. You'll get an `AuthToken` as an argument.
include::partial$params.adoc[tag="failure"]
include::partial$params.adoc[tag="captcha"]
|===

== Response

Type: `Unit`

include::partial$models.adoc[tags="authtoken"]

=== Error

include::partial$models.adoc[tag=reachfiveerror]
